# .github/workflows/bun-ci.yml

name: Bun CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a version like "1.1.0"

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
